#!/usr/bin/env bash

# Original script is made by @mateusauler on GitHub
# https://github.com/ValveSoftware/steam-for-linux/issues/1890#issuecomment-1693548157
# Modified it for general use
#
# Usage: xdg-fakehome <namespace> <bin> [args...]
#
# e.g. xdg-fakehome Steam/fakehome /usr/bin/steam %U
# on steam's .desktop file

namespace=$1
bin=$2
shift 2

export fakeHome="$XDG_DATA_HOME/$namespace"

link_dir() {
  link_name=${1/#"$HOME"/$fakeHome}
  mkdir -p "$(dirname "$link_name")"
  if [ ! -d "$link_name" ]; then
    ln -s "$1" "$link_name"
  fi
}
export -f link_dir

mkdir -p "$fakeHome"
find "$fakeHome" -maxdepth 1 -type l -delete
# shellcheck disable=SC2016
find "$HOME" -maxdepth 1 -print0 | xargs --max-procs="$(nproc)" -I{} bash -c 'link_dir "$0"' {}

HOME="$fakeHome" exec "$bin" "$@"
